### ISSUE TITLE
'@py' backend under Windows

### ISSUE THREAD

**Issue by mtenders** [bicarlsen/easy-scpi#1]
Im using the `pyvisa-py` backend under Windows. When I try connect to an Instrument and set the backend to '@py' explicitly, I get the following error:

```
SerialException: could not open port 'COMCOM7': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
```

If I don't set any backend it works flawlessly. I think removing the following if-clause would solve the problem:
https://github.com/bicarlsen/easy-scpi/blob/49590cf5db492167a1df815064eac5d3ea958473/easy_scpi/scpi_instrument.py#L238-L247

I didn't open  a pull request, because I wasn't sure if the if-clause is needed for something.

**Comment by bicarlsen** [comment]
Can you also post your code that is throwing the error.

**Comment by mtenders** [comment]
```python
import easy_scpi as scpi

inst = scpi.Instrument('COM7', backend='@py')
inst.connect()
```

I also get the same error if I write `'7'` instead of `'COM7'`

**Comment by bicarlsen** [comment]
I tried to replicate the error, but wasn't able to. 

Can you run 
```python
import visa
rm = visa.ResourceManager( '@py' )
rm.list_resources()
```
and post the output.

**Comment by mtenders** [comment]
I get:
```python
('ASRL1::INSTR', 'ASRL7::INSTR')
```

**Comment by bicarlsen** [comment]
It appears that you are correct, that if the originally mentioned `if` clause on line 241 is removed it will resolve the issue. Can you try this and verify? If so, feel free to do a pull request, otherwise I will fix it on my side.

**Comment by mtenders** [comment]
I tried earlier today and everything seemed to work. I make a pull request. Thanks a lot for the quick replies!
