### ISSUE TITLE
Add support for queries with a parameter

### ISSUE THREAD

**Issue by CrocodileDandy** [bicarlsen/easy-scpi#14]
Dear Brian,

I have a TCPIP instrument whose API includes some parametrized SCPI queries in the form of `:STUFf:THINg?[<wsp>MIN|MAX|DEF|SET|ACT|ALL]` and I can't find how to perform those queries using `easy_scpi`.

Trying:
```python
my_instrument.stuff.thing('MIN')
```
would return a fixed `int` (let's say 24 for instance). `easy_scpi` does no processing of the response so I believe this integer is genuinely sent back by the instrument although its documentation does not mention it.

Am I doing it wrong or is it not yet supported by `easy_scpi`?

Thank you for your time and your great abstraction work in this module.

**Comment by bicarlsen** [comment]
Thank you :)

For this you probably need to use the `query` method.
```python
result = my_instrument.query("STUFF:THING? MIN")
```

If arguments are passed it is assumed the statement is a command.

**Comment by bicarlsen** [comment]
PR #18 implements this functionality.
