### ISSUE TITLE
Awkward passing of serial device on linux

### ISSUE THREAD

**Issue by bavovanachte** [bicarlsen/easy-scpi#3]
Hi!

Thanks for this initiative. I'm trying to use this library to communicate with a SCPI-enabled device over a serial link, running in linux.

The serial device that it's connected to is `/dev/ttyACM0` and the underlying port that should be passed on to pyvisa should be `ASRL/dev/ttyACM0::INSTR`. 

To make this work, I need to initialize the instrument using

```inst = scpi.Instrument("COM/dev/ttyACM0")```, which is a bit awkward under linux as the "COM" terminology isn't used there.

**Comment by bicarlsen** [comment]
Unfortunately I don't have a Linux machine to test this with.
Can you please pull the new code and test it out before I push it to PyPI?

**Comment by bicarlsen** [comment]
Hey @bavovanachte ,

I wanted to see if you were able to test the new package. If so, please let me know the results. 

If I don't hear from you in a few days I will close this issue.

**Comment by bavovanachte** [comment]
Apologies for the delay. I've switched to just using PyVisa for now, but plan to try your library again at some point. I'll reopen or open another issue if it doesn't work

**Comment by bicarlsen** [comment]
This should be resolved in [version 0.1.1](https://pypi.org/project/easy-scpi/0.1.1/).
