### ISSUE TITLE
GPIB Support

### ISSUE THREAD

**Issue by nfrancque** [bicarlsen/easy-scpi#6]
Looks like only COM and USB are supported, but PyVisa supports GPIB, so this should be a simple change?

**Comment by bicarlsen** [comment]
I don't have any GPIB instruments I can test with. If you do, give it a shot and let me know if it works, and if not what the specific error is and we can try to get it working.

**Comment by bicarlsen** [comment]
Thanks to @bmjones2 for the fix. This is now available in version 0.1.3.
