### ISSUE TITLE
Problem with sending commands - no termination sign

### ISSUE THREAD

**Issue by Cosik** [bicarlsen/easy-scpi#9]
Hi, I have a problem with sending commands over TCPIP using this lib.

Simple code:
`inst = scpi.Instrument(port_match=False)
inst.rid='TCPIP0::192.168.8.211::30000::SOCKET'
inst.connect()
print(inst.id())`

`TCPIP0::192.168.8.211::30000::SOCKET
Traceback (most recent call last):
    return self.query( '*IDN?' )
    raise errors.VisaIOError(rv)
pyvisa.errors.VisaIOError: VI_ERROR_TMO (-1073807339): Timeout expired before operation completed.`

What I observe is that even to use pyvisa manager I have to set termination sign. I tried in such way:
```
inst.__inst.read_termination = '\n'
inst.__inst.write_termination = '\n'
```
But it is not working this should be set in such way:
self.__inst = self.__rm.open_resource( self.rid, read_termination = '\n', write_termination = '\n')

Do you have any workaround or hint how to fix that without changing a code??

`pip list
Package           Version
----------------- -------
easy-scpi         0.1.4
modbus-tk         1.1.2
pip               21.2.3
pymodbus          3.0.2
pyserial          3.5
PyVISA            1.13.0
PyVISA-py         0.6.0
setuptools        57.4.0
typing_extensions 4.4.0`

**Comment by bicarlsen** [comment]
If I understand correctly you are trying to set the read and write termination characters. This can be done by setting it directly on the `SCPI_Instrument` during initialization as passed in via the [`**resource_params`](https://pyvisa.readthedocs.io/en/latest/api/resources.html).
```python
import easy_scpi as scpi

inst = scpi.Instrument(<port>, read_termination='\n', write_termination='\n')
```
You can see an example of this in the [full example](https://github.com/bicarlsen/easy-scpi#for-use-with-tektronix-pws4305) on the README.

**Comment by Cosik** [comment]
Hi,

Sorry, I've missed somehow this information. Btw very good job with this library :)

**Comment by bicarlsen** [comment]
Happy to help, and glad you are finding the package useful :) Please feel free to raise another issue if you run into any trouble.
